# Generated by Django 4.0.5 on 2022-06-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('paymeuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (2, 'done')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='types/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='types/icons/')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PicturesMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/2022-6-6/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('name', models.CharField(max_length=224)),
                ('title', models.CharField(max_length=224)),
                ('order_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('cost', models.IntegerField(null=True)),
                ('discount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('gpu', models.CharField(blank=True, max_length=224, null=True)),
                ('cpu', models.CharField(blank=True, max_length=224, null=True)),
                ('power', models.CharField(blank=True, max_length=224, null=True)),
                ('display', models.CharField(blank=True, max_length=224, null=True)),
                ('ram', models.CharField(blank=True, max_length=224, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.category')),
                ('pictures', models.ManyToManyField(blank=True, to='shop.picturesmedicine')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Оплата при доставке'), (2, 'Кредитная карта'), (3, 'Прямой банковский перевод')], default=2)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'Ошибка'), (3, 'Завершено'), (4, 'Отменен'), (5, 'Истёк'), (6, 'Возвращен')], default=1)),
                ('delivery_status', models.PositiveSmallIntegerField(choices=[(1, 'В ожидании'), (2, 'На доставке'), (3, 'Доставлен'), (4, 'Возвращен')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_products', models.ManyToManyField(to='shop.cartmodel')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='paymeuz.card')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.deliveryman')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.deliveryaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.product'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/advertising/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.product')),
            ],
        ),
    ]
