# Generated by Django 4.0.5 on 2022-06-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PicturesMedicine',
            new_name='Pictures',
        ),
    ]
