# Generated by Django 4.0.5 on 2022-06-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymeuz', '0001_initial'),
        ('shop', '0002_product_cpu_product_display_product_gpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='paymeuz.card'),
        ),
    ]
